title: Open Science Winter School: Synthetic Data
description: Fake it â€˜till you make it: Generating synthetic data with high utility in R
theme: jekyll-theme-minimal
github:
    is_project_page: false
